#!/usr/bin/env python3
"""Generate Rust code that embeds all theme files as static byte arrays."""

import os
import sys

THEMES_DIR = os.path.join(os.path.dirname(__file__), "themes")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "src", "themes_embed.rs")

def generate():
    themes = []
    for f in sorted(os.listdir(THEMES_DIR)):
        if f.endswith(".tmTheme"):
            themes.append(f)
    
    lines = []
    lines.append("// Auto-generated by generate_themes.py - do not edit manually")
    lines.append("// Embedded theme files for mordant")
    lines.append("")
    
    for theme_file in themes:
        # Create a safe variable name from the filename
        var_name = theme_file.replace(".", "_").replace(" ", "_").replace("(", "_").replace(")", "_").replace("-", "_").replace("+", "_")
        var_name = var_name.rstrip("_")
        # Ensure variable doesn't start with a digit (invalid in Rust)
        if var_name[0].isdigit():
            var_name = "T_" + var_name
        
        file_path = os.path.join(THEMES_DIR, theme_file)
        with open(file_path, "rb") as f:
            content = f.read()
        
        # Write as Rust byte array
        lines.append(f"// Theme: {theme_file}")
        lines.append(f"static {var_name}: &[u8] = &[")
        
        # Write bytes in chunks of 16 per line
        for i in range(0, len(content), 16):
            chunk = content[i:i+16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"    {hex_str},")
        
        lines.append("];")
        lines.append("")
    
    # Generate the registration code
    lines.append("// Register all embedded themes")
    lines.append("pub fn register_embedded_themes(ts: &mut ThemeSet) -> Vec<String> {")
    lines.append("    let mut loaded = Vec::new();")
    lines.append("")
    
    for theme_file in themes:
        var_name = theme_file.replace(".", "_").replace(" ", "_").replace("(", "_").replace(")", "_").replace("-", "_").replace("+", "_")
        var_name = var_name.rstrip("_")
        if var_name[0].isdigit():
            var_name = "T_" + var_name
        theme_name = theme_file.replace(".tmTheme", "")
        lines.append(f"    register_embedded_theme(ts, \"{theme_name}\", {var_name});")
        lines.append(f"    loaded.push(\"{theme_name}\".to_string());")
    
    lines.append("")
    lines.append("    loaded")
    lines.append("}")
    lines.append("")
    lines.append("// Helper function to register a single theme")
    lines.append("fn register_embedded_theme(ts: &mut ThemeSet, name: &str, content: &[u8]) {")
    lines.append("    if let Ok(theme) = ThemeSet::load_from_reader(&mut Cursor::new(content)) {")
    lines.append("        ts.themes.insert(name.to_string(), theme);")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))
    
    print(f"Generated {OUTPUT_FILE} with {len(themes)} embedded themes")

if __name__ == "__main__":
    generate()
